src/Entity/Attributes.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Serializer\Annotation\Groups;

/**
 * @ORM\Entity(repositoryClass="App\Repository\AttributesRepository")
 */
class Attributes
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=50)
     * @Groups("get:read")
     */
    private $key_attribute;

    /**
     * @ORM\Column(type="string", length=50)
     * @Groups("get:read")
     */
    private $value;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\States", inversedBy="attributes")
     */
    private $states;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getKeyAttribute(): ?string
    {
        return $this->key_attribute;
    }

    public function setKeyAttribute(string $key_attribute): self
    {
        $this->key_attribute = $key_attribute;

        return $this;
    }

    public function getValue(): ?string
    {
        return $this->value;
    }

    public function setValue(string $value): self
    {
        $this->value = $value;

        return $this;
    }

    public function getStates(): ?States
    {
        return $this->states;
    }

    public function setStates(?States $states): self
    {
        $this->states = $states;

        return $this;
    }

    public function __toString(): string
    {
        return $this->key_attribute;
    }
}

src/Form/AttributesType.php
<?php

namespace App\Form;

use App\Entity\Attributes;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class AttributesType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('key_attribute')
            ->add('value')
            ->add('states')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Attributes::class,
        ]);
    }
}

src/Controller/AttributesController.php
<?php

namespace App\Controller;

use App\Entity\Attributes;
use App\Form\AttributesType;
use App\Repository\AttributesRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;

/**
 * @Route("/attributes")
 * @IsGranted("ROLE_ADMIN")
 */
class AttributesController extends AbstractController
{
    /**
     * @Route("/", name="attributes_index", methods={"GET"})
     */
    public function index(AttributesRepository $attributesRepository): Response
    {
        return $this->render('attributes/index.html.twig', [
            'attributes' => $attributesRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="attributes_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $attribute = new Attributes();
        $form = $this->createForm(AttributesType::class, $attribute);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($attribute);
            $entityManager->flush();

            return $this->redirectToRoute('attributes_index');
        }

        return $this->render('attributes/new.html.twig', [
            'attribute' => $attribute,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="attributes_show", methods={"GET"})
     */
    public function show(Attributes $attribute): Response
    {
        return $this->render('attributes/show.html.twig', [
            'attribute' => $attribute,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="attributes_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Attributes $attribute): Response
    {
        $form = $this->createForm(AttributesType::class, $attribute);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('attributes_index');
        }

        return $this->render('attributes/edit.html.twig', [
            'attribute' => $attribute,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="attributes_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Attributes $attribute): Response
    {
        if ($this->isCsrfTokenValid('delete'.$attribute->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($attribute);
            $entityManager->flush();
        }

        return $this->redirectToRoute('attributes_index');
    }
}

templates/attributes/_delete_form.html.twig
<form method="post" action="{{ path('attributes_delete', {'id': attribute.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ attribute.id) }}">
    <button class="btn">Delete</button>
</form>

templates/attributes/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Attributs{% endblock %}

{% block body %}
    <h1>Attributs</h1>

    {{ include('attributes/_form.html.twig', {'button_label': 'Sauvegarder'}) }}

    <a href="{{ path('attributes_index') }}">Retour à la liste</a>

    {{ include('attributes/_delete_form.html.twig') }}
{% endblock %}

templates/attributes/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Attributs{% endblock %}

{% block body %}
    <h1 class="h3 mb-2 text-gray-800">Attributs</h1>
          <p class="mb-4">Lorem ipsum.Lorem ipsum.Lorem ipsum.Lorem ipsum.Lorem ipsum.</p>

    <div class="card shadow mb-4">
            <div class="card-header py-3">
              <h6 class="m-0 font-weight-bold text-primary">Attributs</h6>
            </div>
            <div class="card-body">
              <div class="table-responsive">
                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                  <thead>
            <tr>
                <th>Id</th>
                <th>Clé attribut</th>
                <th>Valeur</th>
                <th>Intéragir</th>
            </tr>
        </thead>
        <tbody>
        {% for attribute in attributes %}
            <tr>
                <td>{{ attribute.id }}</td>
                <td>{{ attribute.keyAttribute }}</td>
                <td>{{ attribute.value }}</td>
                <td>
                    <a href="{{ path('attributes_show', {'id': attribute.id}) }}">Voir</a>
                    <a href="{{ path('attributes_edit', {'id': attribute.id}) }}">Modifier</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="4">Aucune entrée trouver</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('attributes_new') }}">Créer une nouvelle entrée</a>
{% endblock %}

templates/attributes/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Attributs{% endblock %}

{% block body %}
    <h1>Créer un nouvel Attributs</h1>

    {{ include('attributes/_form.html.twig') }}

    <a href="{{ path('customers_index') }}">Retour à la liste</a>
{% endblock %}

templates/attributes/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Attributs{% endblock %}

{% block body %}
    <h1>Attributs</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ attribute.id }}</td>
            </tr>
            <tr>
                <th>Clé attribut</th>
                <td>{{ attribute.keyAttribute }}</td>
            </tr>
            <tr>
                <th>Valeur</th>
                <td>{{ attribute.value }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('attributes_index') }}">Retour à la liste</a> <br>

    <a href="{{ path('attributes_edit', {'id': attribute.id}) }}">Modifier</a>

    {{ include('attributes/_delete_form.html.twig') }}
{% endblock %}