src/Entity/Conditions.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ConditionsRepository")
 */
class Conditions
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=50)
     */
    private $key_condition;

    /**
     * @ORM\Column(type="string", length=50)
     */
    private $value;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\States", inversedBy="conditions")
     */
    private $states;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getKeyCondition(): ?string
    {
        return $this->key_condition;
    }

    public function setKeyCondition(string $key_condition): self
    {
        $this->key_condition = $key_condition;

        return $this;
    }

    public function getValue(): ?string
    {
        return $this->value;
    }

    public function setValue(string $value): self
    {
        $this->value = $value;

        return $this;
    }

    public function getStates(): ?States
    {
        return $this->states;
    }

    public function setStates(?States $states): self
    {
        $this->states = $states;

        return $this;
    }

    public function __toString(): string
    {
        return $this->key_condition;
    }
}

src/Form/ConditionsType.php
<?php

namespace App\Form;

use App\Entity\Conditions;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ConditionsType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('key_condition')
            ->add('value')
            ->add('states')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Conditions::class,
        ]);
    }
}

src/Controller/ConditionsController.php
<?php

namespace App\Controller;

use App\Entity\Conditions;
use App\Form\ConditionsType;
use App\Repository\ConditionsRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;

/**
 * @Route("/conditions")
 * @IsGranted("ROLE_ADMIN")
 */
class ConditionsController extends AbstractController
{
    /**
     * @Route("/", name="conditions_index", methods={"GET"})
     */
    public function index(ConditionsRepository $conditionsRepository): Response
    {
        return $this->render('conditions/index.html.twig', [
            'conditions' => $conditionsRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="conditions_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $condition = new Conditions();
        $form = $this->createForm(ConditionsType::class, $condition);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($condition);
            $entityManager->flush();

            return $this->redirectToRoute('conditions_index');
        }

        return $this->render('conditions/new.html.twig', [
            'condition' => $condition,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="conditions_show", methods={"GET"})
     */
    public function show(Conditions $condition): Response
    {
        return $this->render('conditions/show.html.twig', [
            'condition' => $condition,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="conditions_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Conditions $condition): Response
    {
        $form = $this->createForm(ConditionsType::class, $condition);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('conditions_index');
        }

        return $this->render('conditions/edit.html.twig', [
            'condition' => $condition,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="conditions_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Conditions $condition): Response
    {
        if ($this->isCsrfTokenValid('delete'.$condition->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($condition);
            $entityManager->flush();
        }

        return $this->redirectToRoute('conditions_index');
    }
}

templates/conditions/_delete_form.html.twig
<form method="post" action="{{ path('conditions_delete', {'id': condition.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ condition.id) }}">
    <button class="btn">Delete</button>
</form>

templates/conditions/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Conditions{% endblock %}

{% block body %}
    <h1>Conditions</h1>

    {{ include('conditions/_form.html.twig', {'button_label': 'Sauvegarder'}) }}

    <a href="{{ path('conditions_index') }}">Retour à la liste</a>

    {{ include('conditions/_delete_form.html.twig') }}
{% endblock %}

templates/conditions/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Conditions{% endblock %}

{% block body %}

    <div class="card shadow mb-4">
            <div class="card-header py-3">
              <h6 class="m-0 font-weight-bold text-primary">Conditions</h6>
            </div>
            <div class="card-body">
              <div class="table-responsive">
                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                  <thead>
            <tr>
                <th>Id</th>
                <th>Clé condition</th>
                <th>Valeur</th>
                <th>Intéragir</th>
            </tr>
        </thead>
        <tbody>
        {% for condition in conditions %}
            <tr>
                <td>{{ condition.id }}</td>
                <td>{{ condition.keyCondition }}</td>
                <td>{{ condition.value }}</td>
                <td>
                    <a href="{{ path('conditions_show', {'id': condition.id}) }}">Voir</a>
                    <a href="{{ path('conditions_edit', {'id': condition.id}) }}">Modifier</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="4">Aucune entrée trouver</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('conditions_new') }}">Créer une nouvelle entrée</a>
{% endblock %}

templates/conditions/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Nouvelle Condition{% endblock %}

{% block body %}
    <h1>Créer une nouvelle Condition</h1>

    {{ include('conditions/_form.html.twig') }}

    <a href="{{ path('conditions_index') }}">Retour à la liste</a>
{% endblock %}

templates/conditions/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Conditions{% endblock %}

{% block body %}
<h1 class="h3 mb-2 text-gray-800">Conditions</h1>
          <p class="mb-4">Lorem ipsum.Lorem ipsum.Lorem ipsum.Lorem ipsum.Lorem ipsum.</p>

    <div class="card shadow mb-4">
            <div class="card-header py-3">
              <h6 class="m-0 font-weight-bold text-primary">{{customer.company}}</h6>
            </div>
            <div class="card-body">
              <div class="table-responsive">
                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">

        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ condition.id }}</td>
            </tr>
            <tr>
                <th>Key_condition</th>
                <td>{{ condition.keyCondition }}</td>
            </tr>
            <tr>
                <th>Value</th>
                <td>{{ condition.value }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('conditions_index') }}">Retour à la liste</a> <br>

    <a href="{{ path('conditions_edit', {'id': condition.id}) }}">Modifier</a>

    {{ include('conditions/_delete_form.html.twig') }}
{% endblock %}