src/Entity/Actions.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Serializer\Annotation\Groups;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ActionsRepository")
 */
class Actions
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=50)
     * @Groups("get:read")
     */
    private $key_action;

    /**
     * @ORM\Column(type="string", length=50)
     * @Groups("get:read")
     */
    private $value;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\States", inversedBy="actions")
     */
    private $states;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getKeyAction(): ?string
    {
        return $this->key_action;
    }

    public function setKeyAction(string $key_action): self
    {
        $this->key_action = $key_action;

        return $this;
    }

    public function getValue(): ?string
    {
        return $this->value;
    }

    public function setValue(string $value): self
    {
        $this->value = $value;

        return $this;
    }

    public function getStates(): ?States
    {
        return $this->states;
    }

    public function setStates(?States $states): self
    {
        $this->states = $states;

        return $this;
    }

    public function __toString(): string
    {
        return $this->key_action;
    }
}

src/Form/ActionsType.php
<?php

namespace App\Form;

use App\Entity\Actions;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ActionsType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('key_action')
            ->add('value')
            ->add('states')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Actions::class,
        ]);
    }
}

src/Controller/ActionsController.php
<?php

namespace App\Controller;

use App\Entity\Actions;
use App\Form\ActionsType;
use App\Repository\ActionsRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;

/**
 * @Route("/actions")
 * @IsGranted("ROLE_ADMIN")
 */
class ActionsController extends AbstractController
{
    /**
     * @Route("/", name="actions_index", methods={"GET"})
     */
    public function index(ActionsRepository $actionsRepository): Response
    {
        return $this->render('actions/index.html.twig', [
            'actions' => $actionsRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="actions_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $action = new Actions();
        $form = $this->createForm(ActionsType::class, $action);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($action);
            $entityManager->flush();

            return $this->redirectToRoute('actions_index');
        }

        return $this->render('actions/new.html.twig', [
            'action' => $action,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="actions_show", methods={"GET"})
     */
    public function show(Actions $action): Response
    {
        return $this->render('actions/show.html.twig', [
            'action' => $action,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="actions_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Actions $action): Response
    {
        $form = $this->createForm(ActionsType::class, $action);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('actions_index');
        }

        return $this->render('actions/edit.html.twig', [
            'action' => $action,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="actions_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Actions $action): Response
    {
        if ($this->isCsrfTokenValid('delete'.$action->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($action);
            $entityManager->flush();
        }

        return $this->redirectToRoute('actions_index');
    }
}

templates/actions/_delete_form.html.twig
<form method="post" action="{{ path('actions_delete', {'id': action.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ action.id) }}">
    <button class="btn">Delete</button>
</form>

templates/actions/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Modifier une action{% endblock %}

{% block body %}
    <h1>Modifier une action</h1>

    {{ include('actions/_form.html.twig', {'button_label': 'Sauvegarder'}) }}

    <a href="{{ path('actions_index') }}">Retour à la liste</a>

    {{ include('actions/_delete_form.html.twig') }}
{% endblock %}

templates/actions/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Actions{% endblock %}

{% block body %}
    <h1 class="h3 mb-2 text-gray-800">Actions</h1>
          <p class="mb-4">Lorem ipsum.Lorem ipsum.Lorem ipsum.Lorem ipsum.Lorem ipsum.</p>

    <div class="card shadow mb-4">
            <div class="card-header py-3">
              <h6 class="m-0 font-weight-bold text-primary">Actions</h6>
            </div>
            <div class="card-body">
              <div class="table-responsive">
                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                  <thead>
            <tr>
                <th>Id</th>
                <th>Clé action</th>
                <th>Valeur</th>
                <th>Intéragir</th>
            </tr>
        </thead>
        <tbody>
        {% for action in actions %}
            <tr>
                <td>{{ action.id }}</td>
                <td>{{ action.keyAction }}</td>
                <td>{{ action.value }}</td>
                <td>
                    <a href="{{ path('actions_show', {'id': action.id}) }}">Voir</a>
                    <a href="{{ path('actions_edit', {'id': action.id}) }}">Modifier</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="4">Aucune entrée trouver</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('actions_new') }}">Créer une nouvelle entrée</a>
{% endblock %}

templates/actions/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Nouvelle Actions{% endblock %}

{% block body %}
    <h1>Créer un nouvelle actions</h1>

    {{ include('actions/_form.html.twig') }}

    <a href="{{ path('actions_index') }}">Retour à la liste</a>
{% endblock %}

templates/actions/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Clients{% endblock %}

{% block body %}
<h1 class="h3 mb-2 text-gray-800">Actions</h1>
          <p class="mb-4">Lorem ipsum.Lorem ipsum.Lorem ipsum.Lorem ipsum.Lorem ipsum.</p>

    <div class="card shadow mb-4">
            <div class="card-header py-3">
              <h6 class="m-0 font-weight-bold text-primary">Actions</h6>
            </div>
            <div class="card-body">
              <div class="table-responsive">
                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">

        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ action.id }}</td>
            </tr>
            <tr>
                <th>Key_action</th>
                <td>{{ action.keyAction }}</td>
            </tr>
            <tr>
                <th>Value</th>
                <td>{{ action.value }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('actions_index') }}">Retour à la liste</a> <br>

    <a href="{{ path('actions_edit', {'id': action.id}) }}">Modifier</a>

    {{ include('actions/_delete_form.html.twig') }}
{% endblock %}